### ISSUE TITLE
Can't Get blazor-adminlte to work properly

### ISSUE THREAD

**Issue by igalfsg** [sjefvanleeuwen/blazor-adminlte#13]
I followed the README to add blazor-adminlte to my Blazor WASM project, but it seems to be missing some CSS and other resources. I believe I would have to add the shared project of the repo, is there a full list of all the resources I have to add?

**Comment by sjefvanleeuwen** [comment]
Dear, igaalf, sorry I couldn't get back to you on short notice because of holidays.

You will have to do the following if you want to use out of the box as per the description:

If you want to include the current supported ADMINLTE 3.0.5 static css / js / icons content etc.:

Install-Package Blazorized.AdminLte.Content -Version 3.0.5
or visit https://www.nuget.org/packages/Blazorized.AdminLte.Content/ for more installation options.

This will not include resources such as the profile images, if  you want these you will need to get them from the shared sample site's wwwroot

https://github.com/sjefvanleeuwen/blazor-adminlte/tree/master/src/Blazor.AdminLte.Site.Shared/wwwroot

Hope this helps you.
