### ISSUE TITLE
Card sometimes needs a form tag

### ISSUE THREAD

**Issue by jbennink** [sjefvanleeuwen/blazor-adminlte#5]
Discussion:
Currently the Card Component does not support a Form tag. Some of the dem pages have a Form tag around the card-body and card-footer with form fields in the card-body and a submit button in the Footer.
This feels very  content specific so for now you could aencapsulate the entire card with a form tag but perhaps this will be problematic in the future.
tag: enhancement, question

**Comment by MarijnPessers** [comment]
Hi Johan,
Sjef made the Card, I saw a lot of different uses and refactored it. I am not surprised certain types of implementation have not been added to the Card yet since I have not seen all the uses yet, and they vary slightly a lot of times.
I think that you mean there are sometimes Forms within the card around the body, but often not. 

There are a couple of options:
Making a CardBody Component. So the card body tag which is now `<Body>@Content</Body>` would then look like `<Body><CardBody>@Content</CardBody></Body>`
If you want to add a form wrapper you can make it `<Body><CardForm><CardBody>@Content</CardBody></CardForm></Body>` if you wanted to add a form wrapper.

I feel the downside to this is that you make a lot of components and the more complex the less ease of use. But the upside is that is a lot more versatile and correct.

If Form is the only wrapper used then I would suggest using this approach:
You just add all form properties (in Blazor that should be 0? since you don't need a no target or post/get specification). So basically Card gets an extra parameter: `[Parameter] public bool HasForm { get; set; }`

Then you would have to make this code 
```
<div class="card-body">
    @Body
</div>
```
into
```
@if (HasForm) {
    <form>
        <div class="card-body">
            @Body
        </div>
    </form>
}
else {
    <div class="card-body">
        @Body
    </div>
}
```

I would prefer the last one in this case. Just a simple if statement, clean and visible.

There is a dirty option by using old ASP `@:` to conditionally generate a tag without it counting as a tag... but using that requires more soap to feel clean than I have in my home at the moment...

**Comment by sjefvanleeuwen** [comment]
Resovled in Commit https://github.com/sjefvanleeuwen/blazor-adminlte/commit/35011f91afec8851d59715db68ef35569cd3f8fa as per Marijn's instructions.

**Comment by jbennink** [comment]
I see but now the form can only exist inside the body. The original AdminLte demo site had some cards with controls in the body and the submit button in the Footer (one of my other Pull requests. Th form is then wrapped arount both the body and the footer, and I would even include Header so you could punt controls in there as well and wrap the entire contents inside the Card in a form.

As you said there are a lot of different uses so thats wahy I suggested not wrapping it and leaving it to the user. Perhaps I even want 2 Cards wrapped inside the same Form depending on the layout.

**Comment by sjefvanleeuwen** [comment]
Wondering though about the role of <form> in Blazor app. As the discussion progresses, shall I Remove the <form> from the component so you can wrap it the way indicated? That would be the least opinionated way of doing it I think.

**Comment by sjefvanleeuwen** [comment]
Form tag has been removed in commit https://github.com/sjefvanleeuwen/blazor-adminlte/commit/9696d8f1d76856c108544a93443e721faff977d6
